spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST_DEV}:${MYSQL_PORT_DEV}/jiangnanuetc_dev?useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncodeing=UTF%2D8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME_DEV}
    password: ${MYSQL_PWD_DEV}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    jn.mjz.aiot.maven.repair: debug
  file:
    name: logs/repair-dev.log
